<?php
class AdministracionModel extends BaseModel {
	public $table;
	public $method = null; // metodo que va a ejecutarse, necesario para diferenciar el metodo rows()

	public function __construct($adapter) {
		$this -> table = "periquitojuanito";
		parent::__construct($this -> table, $adapter);
	}
	
	public function rows(){
		switch($this->method){
			case 'getGastosAlumnos':
					$filtroAlumno = isset($_POST["dni"]) ? $_POST["dni"] : ""; 
					return $this -> rowNum("SELECT A.DNI, NOMBRE, APELLIDOS, coalesce(COSTECLASES,0) as COSTECLASES, COSTEMATRICULAS, coalesce(COSTECLASES,0)+COSTEMATRICULAS as TOTAL
    			FROM (SELECT ALUMNO,SUM(IMPORTE)CosteClases FROM PAGOCLASES GROUP BY ALUMNO)CLASES 
    			RIGHT JOIN
        		(SELECT ALUMNO,SUM(PRECIO) CosteMatriculas FROM MATRICULAS RIGHT JOIN OFERTA ON OFERTA = OID_O GROUP BY ALUMNO)MATRICULAS 
    			ON CLASES.ALUMNO=MATRICULAS.ALUMNO
    			LEFT JOIN
        		ALUMNOS A
    			ON A.DNI = MATRICULAS.ALUMNO WHERE A.DNI = '%$filtroAlumno%'");
					break;
					
			case 'getDesgloseGeneral':
					$filtroMes = isset($_POST["mes"]) ? $_POST["mes"] : "";
					$filtroAnyo = isset($_POST["anyo"]) ? $_POST["anyo"] : "";
					return $this->rowNum("SELECT MES,AÑO,PAGOCLASES,MATRICULAS,ITVT,ITVM,PAGOTASAS,REPARAT,REPARAM,SALARIOS,SEGMENS,SEGANU,SEGSEM,SUM(SEGTRIM.IMPORTECUOTA)SEGTRIM FROM(
	 			SELECT MES,AÑO,PAGOCLASES,MATRICULAS,ITVT,ITVM,PAGOTASAS,REPARAT,REPARAM,SALARIOS,SEGMENS,SEGANU,SUM(SEGSEM.IMPORTECUOTA)SEGSEM FROM(
	 			SELECT MES,AÑO,PAGOCLASES,MATRICULAS,ITVT,ITVM,PAGOTASAS,REPARAT,REPARAM,SALARIOS,SEGMENS,SUM(SEGANU.IMPORTECUOTA)SEGANU FROM(
	 			SELECT MES,AÑO,PAGOCLASES,MATRICULAS,ITVT,ITVM,PAGOTASAS,REPARAT,REPARAM,SALARIOS,SUM(SEGMENS.IMPORTECUOTA)SEGMENS FROM
	 			(SELECT MES,AÑO,PAGOCLASES,MATRICULAS,ITVT,ITVM,PAGOTASAS,REPARAT,REPARAM,SUM(SALARIO)SALARIOS FROM(
	 			SELECT DISTINCT EXTRACT(MONTH FROM CAL.C_DATE)MES,EXTRACT(YEAR FROM CAL.C_DATE)AÑO,PAGOCLASES,MATRICULAS,ITVT,ITVM,PAGOTASAS,REPARAT,REPARAM,SP.* FROM Z_CALENDAR CAL
	 			LEFT JOIN
	 			(SELECT FECHACONTRATO F,DNI,SALARIO FROM PROFESORES)SP
	 			ON TO_DATE(TO_CHAR(CONCAT(EXTRACT(YEAR FROM CAL.C_DATE),EXTRACT(MONTH FROM CAL.C_DATE))),'YYYYMM') > TO_DATE(TO_CHAR(CONCAT(EXTRACT(YEAR FROM SP.F),EXTRACT(MONTH FROM
				SP.F))),'YYYYMM')
	 			LEFT JOIN
	 			(SELECT EXTRACT(MONTH FROM FECHA)MES,EXTRACT(YEAR FROM FECHA)AÑO,SUM(IMPORTE)PAGOCLASES FROM PAGOCLASES GROUP BY EXTRACT(MONTH FROM FECHA),EXTRACT(YEAR FROM
				FECHA))PCLASES
	 			ON EXTRACT(MONTH FROM CAL.C_DATE) = PCLASES.MES AND EXTRACT(YEAR FROM CAL.C_DATE) = PCLASES.AÑO
	 			LEFT JOIN
	 			(SELECT EXTRACT(MONTH FROM FECHA)MES,EXTRACT(YEAR FROM FECHA)AÑO,SUM(PRECIO)MATRICULAS FROM MATRICULAS RIGHT JOIN OFERTA ON OFERTA=OID_O GROUP BY EXTRACT(MONTH FROM
				FECHA),EXTRACT(YEAR FROM FECHA))MATR
	 			ON EXTRACT(MONTH FROM CAL.C_DATE) = MATR.MES AND EXTRACT(YEAR FROM CAL.C_DATE) = MATR.AÑO
	 			LEFT JOIN
	 			(SELECT EXTRACT(MONTH FROM FECHA)MES,EXTRACT(YEAR FROM FECHA)AÑO,SUM(COSTE)ITVT FROM ITVTURISMOS GROUP BY EXTRACT(MONTH FROM FECHA),EXTRACT(YEAR FROM FECHA))ITVT
	 			ON EXTRACT(MONTH FROM CAL.C_DATE) = ITVT.MES AND EXTRACT(YEAR FROM CAL.C_DATE) = ITVT.AÑO
	 			LEFT JOIN
	 			(SELECT EXTRACT(MONTH FROM FECHA)MES,EXTRACT(YEAR FROM FECHA)AÑO,SUM(COSTE)ITVM FROM ITVMOTOCICLETAS GROUP BY EXTRACT(MONTH FROM FECHA),EXTRACT(YEAR FROM FECHA))ITVM
	 			ON EXTRACT(MONTH FROM CAL.C_DATE) = ITVM.MES AND EXTRACT(YEAR FROM CAL.C_DATE) = ITVM.AÑO
	 			LEFT JOIN
	 			(SELECT EXTRACT(MONTH FROM FECHA)MES,EXTRACT(YEAR FROM FECHA)AÑO,SUM(IMPORTE)PAGOTASAS FROM PAGOTASAS GROUP BY EXTRACT(MONTH FROM FECHA),EXTRACT(YEAR FROM
				FECHA))TASAS
	 			ON EXTRACT(MONTH FROM CAL.C_DATE) = TASAS.MES AND EXTRACT(YEAR FROM CAL.C_DATE) = TASAS.AÑO
	 			LEFT JOIN
	 			(SELECT EXTRACT(MONTH FROM FECHA)MES,EXTRACT(YEAR FROM FECHA)AÑO,SUM(COSTE)REPARAT FROM REPARACIONESTURISMOS GROUP BY EXTRACT(MONTH FROM FECHA),EXTRACT(YEAR FROM
				FECHA))REPARAT
	 			ON EXTRACT(MONTH FROM CAL.C_DATE) = REPARAT.MES AND EXTRACT(YEAR FROM CAL.C_DATE) = REPARAT.AÑO
	 			LEFT JOIN
	 			(SELECT EXTRACT(MONTH FROM FECHA)MES,EXTRACT(YEAR FROM FECHA)AÑO,SUM(COSTE)REPARAM FROM REPARACIONESMOTOCICLETAS GROUP BY EXTRACT(MONTH FROM FECHA),EXTRACT(YEAR FROM
				FECHA))REPARAM
	 			ON EXTRACT(MONTH FROM CAL.C_DATE) = REPARAM.MES AND EXTRACT(YEAR FROM CAL.C_DATE) = REPARAM.AÑO
	 			WHERE TO_DATE(TO_CHAR(CONCAT(EXTRACT(YEAR FROM CAL.C_DATE),EXTRACT(MONTH FROM CAL.C_DATE))),'YYYYMM')<sysdate)
	 			GROUP BY MES,AÑO,PAGOCLASES,MATRICULAS,ITVT,ITVM,PAGOTASAS,REPARAT,REPARAM) BALANCE
				LEFT JOIN --seguros mensuales
	 			(SELECT FECHACONTRATO F,TIPOCUOTA,IMPORTECUOTA FROM SEGUROSTURISMOS Where TIPOCUOTA = 'Mensual'
	 			UNION
	 			Select FECHACONTRATO F,TIPOCUOTA,IMPORTECUOTA FROM SEGUROSMOTOCICLETAS Where TIPOCUOTA = 'Mensual')SEGMENS
	 			ON TO_DATE(TO_CHAR(CONCAT(AÑO,MES)),'YYYYMM')>TO_DATE(TO_CHAR(CONCAT(EXTRACT(YEAR FROM SEGMENS.F),EXTRACT(MONTH FROM SEGMENS.F))),'YYYYMM')
	 			GROUP BY MES,AÑO,PAGOCLASES,MATRICULAS,ITVT,ITVM,PAGOTASAS,REPARAT,REPARAM,SALARIOS) BALANCEM
				LEFT JOIN --seguros anuales
				(SELECT FECHACONTRATO,TIPOCUOTA,IMPORTECUOTA FROM SEGUROSTURISMOS Where TIPOCUOTA = 'Anual'
	 			UNION
				Select FECHACONTRATO,TIPOCUOTA,IMPORTECUOTA FROM SEGUROSMOTOCICLETAS Where TIPOCUOTA = 'Anual') SEGANU
	 			ON MES = 12 AND AÑO >= EXTRACT(YEAR FROM SEGANU.FECHACONTRATO)
	 			GROUP BY MES,AÑO,PAGOCLASES,MATRICULAS,ITVT,ITVM,PAGOTASAS,REPARAT,REPARAM,SALARIOS,SEGMENS) BALANCEMAN
	 			LEFT JOIN --seguros semestrales
	 			(SELECT FECHACONTRATO F,TIPOCUOTA,IMPORTECUOTA FROM SEGUROSTURISMOS Where TIPOCUOTA = 'Semestral'
	 			UNION
				Select FECHACONTRATO F,TIPOCUOTA,IMPORTECUOTA FROM SEGUROSMOTOCICLETAS Where TIPOCUOTA = 'Semestral') SEGSEM
	 			ON (MES = 6 OR MES = 12) AND TO_DATE(TO_CHAR(CONCAT(AÑO,MES)),'YYYYMM')>TO_DATE(TO_CHAR(CONCAT(EXTRACT(YEAR FROM SEGSEM.F),EXTRACT(MONTH FROM SEGSEM.F))),'YYYYMM')
	 			GROUP BY MES,AÑO,PAGOCLASES,MATRICULAS,ITVT,ITVM,PAGOTASAS,REPARAT,REPARAM,SALARIOS,SEGMENS,SEGANU) BALANCEMANSE
	 			LEFT JOIN --seguros trimestrales
	 			(SELECT FECHACONTRATO F,TIPOCUOTA,IMPORTECUOTA FROM SEGUROSTURISMOS Where TIPOCUOTA = 'Trimestral'
	 			UNION
	 			Select FECHACONTRATO F,TIPOCUOTA,IMPORTECUOTA FROM SEGUROSMOTOCICLETAS Where TIPOCUOTA = 'Trimestral') SEGTRIM
	 			ON (MES = 3 OR MES = 6 OR MES = 9 OR MES = 12) AND TO_DATE(TO_CHAR(CONCAT(AÑO,MES)),'YYYYMM')>TO_DATE(TO_CHAR(CONCAT(EXTRACT(YEAR FROM SEGTRIM.F),
				EXTRACT(MONTH FROM SEGTRIM.F))),'YYYYMM')
	 			WHERE (TO_CHAR(TO_DATE(MES,'MM'),'MONTH') LIKE UPPER(CONCAT(CONCAT('%','$filtroMes'),'%')) OR TO_CHAR(MES) LIKE CONCAT(CONCAT('%','$filtroMes'),'%'))
	 			AND TO_CHAR(AÑO) LIKE CONCAT(CONCAT('%','$filtroAnyo'),'%')
	 			GROUP BY MES,AÑO,PAGOCLASES,MATRICULAS,ITVT,ITVM,PAGOTASAS,REPARAT,REPARAM,SALARIOS,SEGMENS,SEGANU,SEGSEM
	 			ORDER BY AÑO,MES");
					break;

			default:
				return $this -> rowNum("SELECT * FROM periquitojuanito");
		}
	}
	
	//	ADMINISTRADOR
	
	public function getGastosAlumnos(){
		$filtroAlumno = isset($_POST["dni"]) ? $_POST["dni"] : "";		
		$query = "SELECT A.DNI, NOMBRE, APELLIDOS, coalesce(COSTECLASES,0) as COSTECLASES, COSTEMATRICULAS, coalesce(COSTECLASES,0)+COSTEMATRICULAS as TOTAL
    		FROM (SELECT ALUMNO,SUM(IMPORTE)CosteClases FROM PAGOCLASES GROUP BY ALUMNO)CLASES 
    		RIGHT JOIN
        	(SELECT ALUMNO,SUM(PRECIO) CosteMatriculas FROM MATRICULAS RIGHT JOIN OFERTA ON OFERTA = OID_O GROUP BY ALUMNO)MATRICULAS 
    		ON CLASES.ALUMNO=MATRICULAS.ALUMNO
    		LEFT JOIN
        	ALUMNOS A
    		ON A.DNI = MATRICULAS.ALUMNO WHERE A.DNI = '%$filtroAlumno%'";
		$tabla = $this->ejecutaSql($query);
		return $tabla;
	}
	
	public function getDesgloseGeneral($first = 0, $last = -1){
		$filtroMes = isset($_POST["mes"]) ? $_POST["mes"] : "";
		$filtroAnyo = isset($_POST["anyo"]) ? $_POST["anyo"] : "";
		$query = "SELECT MES,AÑO,PAGOCLASES,MATRICULAS,ITVT,ITVM,PAGOTASAS,REPARAT,REPARAM,SALARIOS,SEGMENS,SEGANU,SEGSEM,SUM(SEGTRIM.IMPORTECUOTA)SEGTRIM FROM(
 			SELECT MES,AÑO,PAGOCLASES,MATRICULAS,ITVT,ITVM,PAGOTASAS,REPARAT,REPARAM,SALARIOS,SEGMENS,SEGANU,SUM(SEGSEM.IMPORTECUOTA)SEGSEM FROM(
 			SELECT MES,AÑO,PAGOCLASES,MATRICULAS,ITVT,ITVM,PAGOTASAS,REPARAT,REPARAM,SALARIOS,SEGMENS,SUM(SEGANU.IMPORTECUOTA)SEGANU FROM(
 			SELECT MES,AÑO,PAGOCLASES,MATRICULAS,ITVT,ITVM,PAGOTASAS,REPARAT,REPARAM,SALARIOS,SUM(SEGMENS.IMPORTECUOTA)SEGMENS FROM
 			(SELECT MES,AÑO,PAGOCLASES,MATRICULAS,ITVT,ITVM,PAGOTASAS,REPARAT,REPARAM,SUM(SALARIO)SALARIOS FROM(
 			SELECT DISTINCT EXTRACT(MONTH FROM CAL.C_DATE)MES,EXTRACT(YEAR FROM CAL.C_DATE)AÑO,PAGOCLASES,MATRICULAS,ITVT,ITVM,PAGOTASAS,REPARAT,REPARAM,SP.* FROM Z_CALENDAR CAL
 			LEFT JOIN
 			(SELECT FECHACONTRATO F,DNI,SALARIO FROM PROFESORES)SP
 			ON TO_DATE(TO_CHAR(CONCAT(EXTRACT(YEAR FROM CAL.C_DATE),EXTRACT(MONTH FROM CAL.C_DATE))),'YYYYMM') > TO_DATE(TO_CHAR(CONCAT(EXTRACT(YEAR FROM SP.F),EXTRACT(MONTH FROM
			SP.F))),'YYYYMM')
 			LEFT JOIN
 			(SELECT EXTRACT(MONTH FROM FECHA)MES,EXTRACT(YEAR FROM FECHA)AÑO,SUM(IMPORTE)PAGOCLASES FROM PAGOCLASES GROUP BY EXTRACT(MONTH FROM FECHA),EXTRACT(YEAR FROM
			FECHA))PCLASES
 			ON EXTRACT(MONTH FROM CAL.C_DATE) = PCLASES.MES AND EXTRACT(YEAR FROM CAL.C_DATE) = PCLASES.AÑO
 			LEFT JOIN
 			(SELECT EXTRACT(MONTH FROM FECHA)MES,EXTRACT(YEAR FROM FECHA)AÑO,SUM(PRECIO)MATRICULAS FROM MATRICULAS RIGHT JOIN OFERTA ON OFERTA=OID_O GROUP BY EXTRACT(MONTH FROM
			FECHA),EXTRACT(YEAR FROM FECHA))MATR
 			ON EXTRACT(MONTH FROM CAL.C_DATE) = MATR.MES AND EXTRACT(YEAR FROM CAL.C_DATE) = MATR.AÑO
 			LEFT JOIN
 			(SELECT EXTRACT(MONTH FROM FECHA)MES,EXTRACT(YEAR FROM FECHA)AÑO,SUM(COSTE)ITVT FROM ITVTURISMOS GROUP BY EXTRACT(MONTH FROM FECHA),EXTRACT(YEAR FROM FECHA))ITVT
 			ON EXTRACT(MONTH FROM CAL.C_DATE) = ITVT.MES AND EXTRACT(YEAR FROM CAL.C_DATE) = ITVT.AÑO
 			LEFT JOIN
 			(SELECT EXTRACT(MONTH FROM FECHA)MES,EXTRACT(YEAR FROM FECHA)AÑO,SUM(COSTE)ITVM FROM ITVMOTOCICLETAS GROUP BY EXTRACT(MONTH FROM FECHA),EXTRACT(YEAR FROM FECHA))ITVM
 			ON EXTRACT(MONTH FROM CAL.C_DATE) = ITVM.MES AND EXTRACT(YEAR FROM CAL.C_DATE) = ITVM.AÑO
 			LEFT JOIN
 			(SELECT EXTRACT(MONTH FROM FECHA)MES,EXTRACT(YEAR FROM FECHA)AÑO,SUM(IMPORTE)PAGOTASAS FROM PAGOTASAS GROUP BY EXTRACT(MONTH FROM FECHA),EXTRACT(YEAR FROM
			FECHA))TASAS
 			ON EXTRACT(MONTH FROM CAL.C_DATE) = TASAS.MES AND EXTRACT(YEAR FROM CAL.C_DATE) = TASAS.AÑO
 			LEFT JOIN
 			(SELECT EXTRACT(MONTH FROM FECHA)MES,EXTRACT(YEAR FROM FECHA)AÑO,SUM(COSTE)REPARAT FROM REPARACIONESTURISMOS GROUP BY EXTRACT(MONTH FROM FECHA),EXTRACT(YEAR FROM
			FECHA))REPARAT
 			ON EXTRACT(MONTH FROM CAL.C_DATE) = REPARAT.MES AND EXTRACT(YEAR FROM CAL.C_DATE) = REPARAT.AÑO
 			LEFT JOIN
 			(SELECT EXTRACT(MONTH FROM FECHA)MES,EXTRACT(YEAR FROM FECHA)AÑO,SUM(COSTE)REPARAM FROM REPARACIONESMOTOCICLETAS GROUP BY EXTRACT(MONTH FROM FECHA),EXTRACT(YEAR FROM
			FECHA))REPARAM
 			ON EXTRACT(MONTH FROM CAL.C_DATE) = REPARAM.MES AND EXTRACT(YEAR FROM CAL.C_DATE) = REPARAM.AÑO
 			WHERE TO_DATE(TO_CHAR(CONCAT(EXTRACT(YEAR FROM CAL.C_DATE),EXTRACT(MONTH FROM CAL.C_DATE))),'YYYYMM')<sysdate)
 			GROUP BY MES,AÑO,PAGOCLASES,MATRICULAS,ITVT,ITVM,PAGOTASAS,REPARAT,REPARAM) BALANCE
			LEFT JOIN --seguros mensuales
 			(SELECT FECHACONTRATO F,TIPOCUOTA,IMPORTECUOTA FROM SEGUROSTURISMOS Where TIPOCUOTA = 'Mensual'
 			UNION
 			Select FECHACONTRATO F,TIPOCUOTA,IMPORTECUOTA FROM SEGUROSMOTOCICLETAS Where TIPOCUOTA = 'Mensual')SEGMENS
 			ON TO_DATE(TO_CHAR(CONCAT(AÑO,MES)),'YYYYMM')>TO_DATE(TO_CHAR(CONCAT(EXTRACT(YEAR FROM SEGMENS.F),EXTRACT(MONTH FROM SEGMENS.F))),'YYYYMM')
 			GROUP BY MES,AÑO,PAGOCLASES,MATRICULAS,ITVT,ITVM,PAGOTASAS,REPARAT,REPARAM,SALARIOS) BALANCEM
			LEFT JOIN --seguros anuales
			(SELECT FECHACONTRATO,TIPOCUOTA,IMPORTECUOTA FROM SEGUROSTURISMOS Where TIPOCUOTA = 'Anual'
 			UNION
			Select FECHACONTRATO,TIPOCUOTA,IMPORTECUOTA FROM SEGUROSMOTOCICLETAS Where TIPOCUOTA = 'Anual') SEGANU
 			ON MES = 12 AND AÑO >= EXTRACT(YEAR FROM SEGANU.FECHACONTRATO)
 			GROUP BY MES,AÑO,PAGOCLASES,MATRICULAS,ITVT,ITVM,PAGOTASAS,REPARAT,REPARAM,SALARIOS,SEGMENS) BALANCEMAN
 			LEFT JOIN --seguros semestrales
 			(SELECT FECHACONTRATO F,TIPOCUOTA,IMPORTECUOTA FROM SEGUROSTURISMOS Where TIPOCUOTA = 'Semestral'
 			UNION
			Select FECHACONTRATO F,TIPOCUOTA,IMPORTECUOTA FROM SEGUROSMOTOCICLETAS Where TIPOCUOTA = 'Semestral') SEGSEM
 			ON (MES = 6 OR MES = 12) AND TO_DATE(TO_CHAR(CONCAT(AÑO,MES)),'YYYYMM')>TO_DATE(TO_CHAR(CONCAT(EXTRACT(YEAR FROM SEGSEM.F),EXTRACT(MONTH FROM SEGSEM.F))),'YYYYMM')
 			GROUP BY MES,AÑO,PAGOCLASES,MATRICULAS,ITVT,ITVM,PAGOTASAS,REPARAT,REPARAM,SALARIOS,SEGMENS,SEGANU) BALANCEMANSE
 			LEFT JOIN --seguros trimestrales
 			(SELECT FECHACONTRATO F,TIPOCUOTA,IMPORTECUOTA FROM SEGUROSTURISMOS Where TIPOCUOTA = 'Trimestral'
 			UNION
 			Select FECHACONTRATO F,TIPOCUOTA,IMPORTECUOTA FROM SEGUROSMOTOCICLETAS Where TIPOCUOTA = 'Trimestral') SEGTRIM
 			ON (MES = 3 OR MES = 6 OR MES = 9 OR MES = 12) AND TO_DATE(TO_CHAR(CONCAT(AÑO,MES)),'YYYYMM')>TO_DATE(TO_CHAR(CONCAT(EXTRACT(YEAR FROM SEGTRIM.F),
			EXTRACT(MONTH FROM SEGTRIM.F))),'YYYYMM')
 			WHERE (TO_CHAR(TO_DATE(MES,'MM'),'MONTH') LIKE UPPER(CONCAT(CONCAT('%','$filtroMes'),'%')) OR TO_CHAR(MES) LIKE CONCAT(CONCAT('%','$filtroMes'),'%'))
 			AND TO_CHAR(AÑO) LIKE CONCAT(CONCAT('%','$filtroAnyo'),'%')
 			GROUP BY MES,AÑO,PAGOCLASES,MATRICULAS,ITVT,ITVM,PAGOTASAS,REPARAT,REPARAM,SALARIOS,SEGMENS,SEGANU,SEGSEM
 			ORDER BY AÑO,MES";
 		echo $query;
 		$desglose = $this->consultaPaginada($query, $first, $last);
 		return $desglose;	
	}

}
?>